---
image_resource:
  type: docker-image
  source:
    repository: brenix/alpine-bash-git-ssh
    tag: latest
platform: linux
inputs:
- name: lf-git
- name: lf-release
- name: version
outputs:
- name: version
- name: lf-git-changed
run:
  path: lf-git/ci/scripts/updateChangelog.sh
